### ISSUE TITLE
GARRETT: Create and fill out index2 file

### ISSUE THREAD

**Issue by ayojackay** [ayojackay/collab-practice#1]
## TODO
- [ ] Create a new file and name it: *index2.html*
- [ ] Manually add [Bootstrap Template](https://getbootstrap.com/docs/4.5/getting-started/introduction/#starter-template) to `index2.html` file
- [ ] Inside `body` create a [grid](https://getbootstrap.com/docs/4.5/layout/grid/) with the following:
  - navbar
  - left column
  - right column
  - footer
- [ ] Stylize each section with a `background-color`

### Resources
[Bootstrap Layout Overview](https://getbootstrap.com/docs/4.5/layout/overview/)
[HTML Tags](https://www.tutorialrepublic.com/html-reference/html5-tags.php)
